-- MySQL Script generated by MySQL Workbench
-- Sun Oct 27 18:05:54 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------

DROP TABLE IF EXISTS `mydb`.`Municipio` ;
DROP TABLE IF EXISTS `mydb`.`TabelaUsuario` ;
DROP TABLE IF EXISTS `mydb`.`TabelaANP` ;
DROP TABLE IF EXISTS `mydb`.`Departamento` ;
DROP TABLE IF EXISTS `mydb`.`UploadTabelaFAM` ;
DROP TABLE IF EXISTS `mydb`.`TabelaFAM` ;
DROP TABLE IF EXISTS `mydb`.`NotaFiscal` ;
DROP TABLE IF EXISTS `mydb`.`CupomFiscal` ;
DROP TABLE IF EXISTS `mydb`.`ItemNotaFiscal` ;


CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `id_municipio` INT NOT NULL,
  `nome_municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TabelaUsuario`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`TabelaUsuario` (
  `sgdp` INT NOT NULL COMMENT 'Código identificador da tabela.\n',
  `id_municipio_refente` INT NOT NULL,
  `id_municipio` INT NOT NULL,
  `dt_geracao` DATE NOT NULL,
  `ano_referente` VARCHAR(4) NOT NULL,
  `titulo_aba_1` VARCHAR(120) NOT NULL,
  `titulo_aba_2` VARCHAR(120) NOT NULL,
  `titulo_aba_3` VARCHAR(120) NOT NULL,
  `analista_resp` VARCHAR(90) NULL,
  PRIMARY KEY (`sgdp`),
  CONSTRAINT `fk_TabelaUsuario_Municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `mydb`.`Municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TabelaUsuario_Municipio2`
    FOREIGN KEY (`id_municipio_refente`)
    REFERENCES `mydb`.`Municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TabelaUsuario_Municipio1_idx` ON `mydb`.`TabelaUsuario` (`id_municipio` ASC);

CREATE INDEX `fk_TabelaUsuario_Municipio2_idx` ON `mydb`.`TabelaUsuario` (`id_municipio_refente` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`TabelaANP`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`TabelaANP` (
  `id_municipio` INT NOT NULL,
  `mes` CHAR(2) NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `produto` VARCHAR(45) NOT NULL,
  `preco_medio_revenda` DECIMAL NOT NULL,
  `preco_maximo_revenda` DECIMAL NOT NULL,
  `dt_vigencia_municipio_anp` DATE NULL,
  PRIMARY KEY (`id_municipio`, `mes`, `ano`),
  CONSTRAINT `fk_TabelaANP_Municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `mydb`.`Municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TabelaANP_Municipio1_idx` ON `mydb`.`TabelaANP` (`id_municipio` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `id_dpto` INT NOT NULL,
  `nome_dpto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dpto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`UploadTabelaFAM`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`UploadTabelaFAM` (
  `id_upload` INT NOT NULL,
  `dt_upload` DATE NULL,
  PRIMARY KEY (`id_upload`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TabelaFAM`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`TabelaFAM` (
  `mes` CHAR(2) NOT NULL,
  `ano` CHAR(4) NOT NULL,
  `id_upload` INT NOT NULL,
  `valor_fam` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`mes`, `ano`),
  CONSTRAINT `fk_TabelaFAM_UploadTabelaFAM1`
    FOREIGN KEY (`id_upload`)
    REFERENCES `mydb`.`UploadTabelaFAM` (`id_upload`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_TabelaFAM_UploadTabelaFAM1_idx` ON `mydb`.`TabelaFAM` (`id_upload` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscal`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscal` (
  `id_nota_fiscal` INT NOT NULL,
  `sgdp` INT NOT NULL,
  `id_dpto` INT NOT NULL,
  `mes_fam` CHAR(2) NOT NULL,
  `ano_fam` CHAR(4) NOT NULL,
  `vrtotal` DECIMAL(7,2) NOT NULL,
  `nro_folha` INT NULL,
  `dt_consulta_anp` DATE NULL,
  `veiculo` VARCHAR(50) NULL,
  `placa_veiculo` VARCHAR(7) NULL,
  `dt_emissao` DATE NULL,
  PRIMARY KEY (`id_nota_fiscal`),
  CONSTRAINT `fk_NotaFiscal_TabelaUsuario1`
    FOREIGN KEY (`sgdp`)
    REFERENCES `mydb`.`TabelaUsuario` (`sgdp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotaFiscal_Departamento1`
    FOREIGN KEY (`id_dpto`)
    REFERENCES `mydb`.`Departamento` (`id_dpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotaFiscal_TabelaFAM1`
    FOREIGN KEY (`mes_fam` , `ano_fam`)
    REFERENCES `mydb`.`TabelaFAM` (`mes` , `ano`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_NotaFiscal_TabelaUsuario1_idx` ON `mydb`.`NotaFiscal` (`sgdp` ASC);

CREATE INDEX `fk_NotaFiscal_Departamento1_idx` ON `mydb`.`NotaFiscal` (`id_dpto` ASC);

CREATE INDEX `fk_NotaFiscal_TabelaFAM1_idx` ON `mydb`.`NotaFiscal` (`mes_fam` ASC, `ano_fam` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`CupomFiscal`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`CupomFiscal` (
  `coo` VARCHAR(45) NOT NULL,
  `sgdp` INT NOT NULL,
  `id_nota_fiscal` INT NULL,
  `ecf` VARCHAR(45) NULL,
  `posto_referente` VARCHAR(90) NULL,
  `hodometro` INT NULL,
  `cliente` VARCHAR(90) NULL,
  `dt_emissao` DATETIME NULL,
  `qtd` INT NULL,
  `vr_unitario` DECIMAL(7,2) NULL,
  PRIMARY KEY (`coo`),
  CONSTRAINT `fk_CupomFiscal_NotaFiscal1`
    FOREIGN KEY (`id_nota_fiscal`)
    REFERENCES `mydb`.`NotaFiscal` (`id_nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CupomFiscal_TabelaUsuario1`
    FOREIGN KEY (`sgdp`)
    REFERENCES `mydb`.`TabelaUsuario` (`sgdp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_CupomFiscal_NotaFiscal1_idx` ON `mydb`.`CupomFiscal` (`id_nota_fiscal` ASC);

CREATE INDEX `fk_CupomFiscal_TabelaUsuario1_idx` ON `mydb`.`CupomFiscal` (`sgdp` ASC);


-- -----------------------------------------------------
-- Table `mydb`.`ItemNotaFiscal`
-- -----------------------------------------------------


CREATE TABLE IF NOT EXISTS `mydb`.`ItemNotaFiscal` (
  `id_nota_fiscal` INT NOT NULL,
  `id_item` INT NOT NULL,
  `vrunitario` DECIMAL(7,2) NOT NULL,
  `id_tipo_combustivel` VARCHAR(45) NOT NULL,
  `qtde` INT NOT NULL,
  PRIMARY KEY (`id_nota_fiscal`, `id_item`),
  CONSTRAINT `fk_ItemNF_NF1`
    FOREIGN KEY (`id_nota_fiscal`)
    REFERENCES `mydb`.`NotaFiscal` (`id_nota_fiscal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_ItemNF_NF1_idx` ON `mydb`.`ItemNotaFiscal` (`id_nota_fiscal` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
