-- MySQL Script generated by MySQL Workbench
-- Thu Oct  3 01:37:01 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Departamento` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Departamento` (
  `id_dpto` INT NOT NULL,
  `nome_dpto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_dpto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Municipio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Municipio` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Municipio` (
  `id_municipio` INT NOT NULL,
  `nome_municipio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_municipio`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NotaFiscal`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NotaFiscal` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NotaFiscal` (
  `id_nota_fiscal` INT NOT NULL,
  `id_dpto` INT NOT NULL,
  `id_tabela_anp` INT NULL,
  `chave_acesso` VARCHAR(44) NOT NULL,
  `nro_folha` INT NULL,
  `dt_consulta_anp` DATE NULL,
  `desc_veiculo` VARCHAR(45) NULL,
  `placa_veiculo` VARCHAR(45) NULL,
  PRIMARY KEY (`id_nota_fiscal`),
  INDEX `fk_NotaFiscal_TabelaANP1_idx` (`id_tabela_anp` ASC) VISIBLE,
  INDEX `fk_NotaFiscal_Departamento1_idx` (`id_dpto` ASC) VISIBLE,
  CONSTRAINT `fk_NotaFiscal_TabelaANP1`
    FOREIGN KEY (`id_tabela_anp`)
    REFERENCES `mydb`.`TabelaANP` (`id_tabela_anp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_NotaFiscal_Departamento1`
    FOREIGN KEY (`id_dpto`)
    REFERENCES `mydb`.`Departamento` (`id_dpto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TabelaANP`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TabelaANP` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TabelaANP` (
  `id_tabela_anp` INT NOT NULL,
  `id_municipio` INT NOT NULL,
  `mes` VARCHAR(2) NOT NULL,
  `ano` VARCHAR(4) NOT NULL,
  `produto` VARCHAR(45) NOT NULL,
  `preco_medio_revenda` DECIMAL NOT NULL,
  `preco_maximo_revenda` DECIMAL NOT NULL,
  `dt_vigencia_municipio_anp` DATE NULL,
  PRIMARY KEY (`id_tabela_anp`),
  INDEX `fk_TabelaANP_Municipio1_idx` (`id_municipio` ASC) VISIBLE,
  CONSTRAINT `fk_TabelaANP_Municipio1`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `mydb`.`Municipio` (`id_municipio`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TabelaUsuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`TabelaUsuario` ;

CREATE TABLE IF NOT EXISTS `mydb`.`TabelaUsuario` (
  `sgdp` INT NOT NULL COMMENT 'Código identificador da tabela.\n',
  `id_tabela_anp` INT NULL,
  `dt_geracao` DATE NOT NULL,
  `mes_referente` VARCHAR(2) NOT NULL,
  `ano_referente` VARCHAR(4) NOT NULL,
  `titulo_aba_1` VARCHAR(120) NOT NULL,
  `titulo_aba_2` VARCHAR(120) NOT NULL,
  `titulo_aba_3` VARCHAR(120) NOT NULL,
  `analista_resp` VARCHAR(90) NULL,
  PRIMARY KEY (`sgdp`),
  INDEX `fk_Tabela_TabelaANP1_idx` (`id_tabela_anp` ASC) VISIBLE,
  CONSTRAINT `fk_Tabela_TabelaANP1`
    FOREIGN KEY (`id_tabela_anp`)
    REFERENCES `mydb`.`TabelaANP` (`id_tabela_anp`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
